on: [push]

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: koki-develop/private-github-actions-example@main
        with:
          who-to-greet: koki

  reusable:
    uses: koki-develop/private-github-actions-example/.github/workflows/_reusable.yml@main

  composite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: koki-develop/private-github-actions-example/.github/actions/hello@main
